### ISSUE TITLE
Publish to crates.io

### ISSUE THREAD

**Issue by fenhl** [PistonDevelopers/hematite_nbt#12]
[Documentation](http://doc.crates.io/crates-io.html#publishing-crates)

Todo:

- [x] Add metadata (#13)
- [x] Move to Rust stable (#17)
- [x] Rename package to `hematite-nbt` (#18)
- [x] Remove wildcard dependencies (#19)
- [x] `cargo publish`

**Comment by fenhl** [comment]
The crate name `nbt` has now been reserved by [FliPPeh/nbt.rs](https://github.com/FliPPeh/nbt.rs) — should we go with `hematite_nbt` then?

**Comment by bvssvni** [comment]
If you use `hematite_nbt` I would prefer the crate name to be the same, but you could have a package name `hematite-nbt` and call the crate `nbt`.

Example: `pistoncore-input` has crate name `input`, while `piston_meta` has same crate name.

**Comment by bvssvni** [comment]
Wrote up the conventions here https://github.com/PistonDevelopers/piston/issues/972.

**Comment by fenhl** [comment]
Sounds good.

**Comment by bvssvni** [comment]
@fenhl When you publish it, could you add me as owner? I need it for https://github.com/PistonDevelopers/piston/issues/968.

**Comment by toqueteos** [comment]
Any ETA on this?

**Comment by fenhl** [comment]
https://crates.io/crates/hematite-nbt :tada:
